---
- name: install dependencies
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      - at
      - bc
      - cmake
      - ffmpeg
      - gmic
      - gnuradio
      - gr-osmosdr
      - imagemagick
      - jq
      - libatlas-base-dev
      - libgfortran5
      - libjpeg9
      - libjpeg9-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libsox-fmt-mp3
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libxft-dev
      - libxft2
      - predict
      - wkhtmltopdf
      - python3-pip
      - python-setuptools
      - socat
      - sox
      - sqlite3
      - certbot

- name: Installing WXtoImg
  become: yes
  apt:
    deb: "{{ noaa_home }}/software/wxtoimg-{{ system_architecture }}-2.11.2-beta.deb"
    state: present
    update_cache: no

#- name: Installing MeteorDemod
#  become: yes
#  apt:
#    deb: "https://github.com/Digitelektro/MeteorDemod/releases/download/2.5.6-beta/meteordemod_2.5.6_{{ system_architecture }}.deb"
#    state: present
#    update_cache: no

- name: Installing SatDump
  become: yes
  apt:
    deb: "{{ noaa_home }}/software/satdump_1.1.0_{{ system_architecture }}.deb"
    state: present
    update_cache: no

- name: Installing AnyDesk remote desktop
  become: yes
  apt:
    deb: "{{ noaa_home }}/software/anydesk_6.3.0-1_{{ system_architecture }}.deb"
    state: present
    update_cache: no
...
